### 
# @name register
POST http://localhost:3000/users/register HTTP/1.1
content-type: application/json

{
  "username": "testuser",
  "email": "testuser@email.com",
  "password": "testpassword"
}



### 
# @name login
POST http://localhost:3000/users/login HTTP/1.1
content-type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}



### 
# @name refreshToken
POST http://localhost:3000/token HTTP/1.1
content-type: application/json

{
  "token": "{{login.response.body.refreshToken}}"
}



### 
# @name logout
DELETE http://localhost:3000/logout HTTP/1.1
content-type: application/json

{
  "token": "{{login.response.body.refreshToken}}"
}


### 
# @name updateUser
PUT http://localhost:3000/users/me HTTP/1.1
Authorization: Bearer {{login.response.body.accessToken}}
content-type: application/json

{
  
  "email": "new2e3mail@email.com"
}


###
GET http://localhost:3000/users 